// Generated by CoffeeScript 1.8.0
(function() {
  var define_controller;

  define('demo', function() {
    var user_plugin;
    return user_plugin = {
      name: 'demo',
      anchor: '#/demo',
      title: 'Demo',
      type: 'plugin',
      icon: 'icon-list',
      init: function() {
        console.log('init');
        define_controller();
        return foundry.initialized(this.name);
      }
    };
  });

  define_controller = function() {
    return angular.module('foundry').controller('DemoController', ['$scope', function($scope) {}]);
  };

}).call(this);
